hellomake: Turbo_Codes.c Deconcatination.c Deinterleaver.c Encoder.c Interleaver.c Max_Function.c Modulating.c Turbo_Testing_code.c boxmuller_noise.c
	gcc -Wall Turbo_Codes.c Deconcatination.c Deinterleaver.c Encoder.c Interleaver.c Max_Function.c Modulating.c boxmuller_noise.c Turbo_Testing_code.c -lm -o output
